### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-wczarnomysy#1]
Hi, @wczarnomysy!!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] Menu items should be clickable
- [x] Humanize text in `alt` attributes, a sentence explaining a blind user what show the image may do the trick.
- [x] Class selectors are free, let's use them instead of tag selectors. Avoid using tag selectors as main, switch them with class selectors.
- [x] Improve hierarchy, we can use the body tag selector to add general styles, like color, background-color, font-family, font-size, and font-weight
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] There are some weird margins, let's remove them: Remember the browser add some margins to the `<body>` element; and Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Remove unused CSS rules ;)

- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

Once you have these fixed try to finish the styles.

Let me know if you have any doubts ;)

Go for it!!

**Comment by wczarnomysy** [comment]
Hi Carlos,
I have followed your tips to finish the exercise and I have uploaded a corrected version to github. 
Please have a look at it  and let me know your comments. 

Thank you,
Weronika

**Comment by oneeyedman** [comment]
Super well done, @wczarnomysy!!!

There is some minor issue (remember the header have a top and bottom padding for the tablet version `padding: 20px 30px`) but it looks great!
